#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/homePage.html.twig
aboutUs:
  path: /aboutUs
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/aboutUsPage.html.twig
services:
  path: /services
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/servicesPage.html.twig
choiceService:
  path: /choiceService
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/newServicesPage.html.twig
business:
  path: /businessPage
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/newBusinesSite.html.twig
designPage:
  path: /designPage
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/newBusinesSite.html.twig
landingPage:
  path: /landingPage
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/newLandingPage.html.twig
seoPage:
  path: /seoPage
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/newSEOPage.html.twig
siteDirectory:
  path: /seoPage
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/newSiteDirectory.html.twig